# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 16:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(help_text='Duration in seconds.')),
                ('notes', models.TextField(blank=True)),
                ('plan', models.TextField()),
                ('result', models.TextField(blank=True)),
                ('focus', models.PositiveSmallIntegerField(blank=True, help_text='Focus level, during the bout. Likert scale, out of seven. Four is neutral, one is very bad, seven is very good.', null=True, validators=[django.core.validators.MaxValueValidator(8)])),
            ],
            options={
                'ordering': ('start_time',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bout',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouts.Project'),
        ),
    ]
