# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouts', '0002_project_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bout',
            name='focus',
            field=models.FloatField(blank=True, help_text='Focus level, during the bout. Likert scale, out of seven. Four is neutral, one is very bad, seven is very good.', null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
    ]
